### ISSUE TITLE
Alterações no metodo apagar conta

### ISSUE THREAD

**Issue by LizCardoso** [TPII20152/SB04#11]
Metodo com defeito: Apaga conta que não existe e retorna uma messagem de sucesso.

**Comment by tallesb** [comment]
@LizCardoso, vou ficar responsável por essa issue!

**Comment by tallesb** [comment]
Bug fixado.
@LizCardoso e @LucasHF, esse bug ocorria por conta de um laço no metodo Apagar nas classes de repositório(ArrayContas).
Commit relacionado:
1afda38aa4c6246611e1c806d57e5707b5986075
